---
- name: restart smbd
  service:
    name: smbd
    state: restarted

- name: restart nmbd
  service:
    name: nmbd
    state: restarted

- name: restart nfs
  service:
    name: nfs-kernel-server
    state: restarted
