---
- name: sysctl
  command: sysctl -p

- name: netfilter-persistent
  command: netfilter-persistent save

- name: systemctl daemon-reload
  command: systemctl daemon-reload
  
- name: restart dhcpcd
  service:
    name: dhcpcd
    state: restarted

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: restart hostapd
  service:
    name: hostapd
    state: restarted
