---
- include_tasks: packages.yml

# - include_tasks: apt.yml
- include_tasks: firewalld.yml
- include_tasks: hostname.yml
- include_tasks: locale.yml
- include_tasks: ssh.yml
- include_tasks: timezone.yml

- include_tasks: static_ip.yml
  # when: hhwm_static_ip == "yes"
