---
- include_tasks: packages.yml

# - include_tasks: apt.yml
# - include_tasks: firewalld.yml
- include_tasks: hostname.yml
- include_tasks: locale.yml
- include_tasks: networkd.yml
- include_tasks: ssh.yml
- include_tasks: timezone.yml

- include_tasks: mount/rp02.yml
  when: inventory_hostname == 'rp02.kade3.dev'
- include_tasks: mount/rp04.yml
  when: inventory_hostname == 'rp04.kade3.dev'
