---
#---------------------------------------------------------------
# deinstall classic networking
#---------------------------------------------------------------
# pi@raspberrypi:~ $ sudo -Es   # if not already done
# root@raspberrypi:~ # systemctl daemon-reload
# root@raspberrypi:~ # systemctl disable --now ifupdown dhcpcd dhcpcd5 isc-dhcp-client isc-dhcp-common rsyslog
# root@raspberrypi:~ # apt --autoremove purge ifupdown dhcpcd dhcpcd5 isc-dhcp-client isc-dhcp-common rsyslog
# root@raspberrypi:~ # rm -r /etc/network /etc/dhcp

#---------------------------------------------------------------
# Remove old configuration files
#---------------------------------------------------------------
- name: networkd | Remove /etc/dhcp
  file:
    path: /etc/dhcp
    state: absent

- name: networkd | Remove /etc/network
  file:
    path: /etc/network
    state: absent

- name: networkd | Remove /etc/wpa_supplicant/wpa_supplicant.conf
  file:
    path: /etc/wpa_supplicant/wpa_supplicant.conf
    state: absent

#---------------------------------------------------------------
# Setup new configuration files
#---------------------------------------------------------------
- name: networkd | Link /etc/resolv.conf
  file:
    state: link
    src: /run/systemd/resolve/stub-resolv.conf 
    dest: /etc/resolv.conf
    force: yes

- name: networkd | Create /etc/systemd/network/10-wired.network (DHCP)
  copy:
    src: networkd/10-wired.network
    dest: /etc/systemd/network/10-wired.network
    owner: root
    group: root
    mode: '0644'
  when: hhwm_static_ip == 'no'
  notify:
    - reboot

- name: networkd | Create /etc/systemd/network/10-wired.network (static)
  template:
    src: networkd/10-wired.network.j2
    dest: /etc/systemd/network/10-wired.network
    owner: root
    group: root
    mode: '0644'
  when: hhwm_static_ip != 'no'
  notify:
    - reboot

- name: networkd | Create /etc/systemd/network/10-wlan.network (DHCP)
  copy:
    src: networkd/10-wlan.network
    dest: /etc/systemd/network/10-wlan.network
    owner: root
    group: root
    mode: '0644'
  when: hhwm_wlan0_enabled == "yes"
  notify:
    - reboot

# rm -f /etc/systemd/network/73-usb-net-by-mac.link
- name: networkd | Remove /etc/systemd/network/73-usb-net-by-mac.link
  file:
    path: /etc/systemd/network/73-usb-net-by-mac.link
    state: absent
  notify:
    - reboot

# rm -f /etc/systemd/network/99-default.link
- name: networkd | Remove /etc/systemd/network/99-default.link
  file:
    path: /etc/systemd/network/99-default.link
    state: absent
  notify:
    - reboot

- name: networkd | Create /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
  template:
    src: networkd/wpa_supplicant-wlan0.conf.j2
    dest: /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
    owner: root
    group: root
    mode: '0600'
  when: hhwm_wlan0_enabled == "yes"
  notify:
    - reboot

- name: networkd | Remove /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
  file:
    path: /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
    state: absent
  when: hhwm_wlan0_enabled != "yes"
  notify:
    - reboot

- name: networkd | Disable wpa_supplicant.service
  systemd:
    name: wpa_supplicant
    enabled: no
    masked: yes
    state: stopped
  notify:
    - reboot

- name: networkd | Enable/Disable wpa_supplicant@wlan0.service
  systemd:
    name: wpa_supplicant@wlan0
    enabled: "{{ hhwm_wlan0_enabled }}"
  notify:
    - reboot

- name: networkd | Enable systemd-networkd.service
  systemd:
    name: systemd-networkd.service
    enabled: yes
  notify:
    - reboot

- name: networkd | Enable systemd-resolved.service
  systemd:
    name: systemd-resolved.service
    enabled: yes
  notify:
    - reboot

- name: networkd | Enable systemd-timesyncd.service
  systemd:
    name: systemd-timesyncd.service
    enabled: yes
  notify:
    - reboot
