#
# /home is a btrfs on a USB drive
#
---
- name: mount/rp04 | Create /etc/systemd/system/home.mount
  copy:
    src: mount/rp04/home.mount
    dest: /etc/systemd/system/home.mount
    owner: root
    group: root
    mode: '0644'
  notify:
    - systemd reload

- name: mount/rp04 | Create /etc/systemd/system/home.automount
  copy:
    src: mount/rp04/home.automount
    dest: /etc/systemd/system/home.automount
    owner: root
    group: root
    mode: '0644'
  notify:
    - systemd reload

- name: mount/rp04 | systemd home.mount
  systemd:
    name: home.mount
    enabled: no

- name: mount/rp04 | systemd home.automount
  systemd:
    name: home.automount
    enabled: yes
    state: started
