---
all:
  hosts:
    # New pi-hole
    rp01:
      ansible_ssh_host: 192.168.10.16
      hhwm_wlan0_enabled: no
    # rp02.kade3.home:
    #   ansible_ssh_host: 192.168.10.35
    # rp04.kade3.home:
    #   ansible_ssh_host: 192.168.10.35

