---
all:
  children:
    # raspberry_pi_zero_w:
    #   hosts:
    #     rp05.kade3.dev:
    #       ansible_host: 192.168.128.254
    raspberry_pi_3:
      hosts:
        # New pi-hole
        rp01.kade3.dev:
          ansible_host: 192.168.128.2
          hhwm_static_ip: 192.168.128.2
        # New proxy
        rp02.kade3.dev:
          ansible_host: 192.168.128.3
          hhwm_static_ip: 192.168.128.3
    raspberry_pi_4:
      hosts:
        rp03.kade3.dev:
          ansible_host: 192.168.128.156
    raspberry_pi_400:
      hosts:
        rp04.kade3.dev:
          ansible_host: 192.168.128.194
